//src/app/layout.sx
import type { Metadata } from "next";
import "./globals.css";
import Providers from "./components/Providers";
import { Poppins } from "next/font/google";
import ProtectedLayout from "@/auth/ProtectedLayout";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
